In [32]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.svm import LinearSVC
from sklearn.multiclass import OneVsOneClassifier
from sklearn import cross_validation

In [33]:
df = pd.read_excel("students_dataSet.xls")
print (df)

      sslc  hsc  cgpa  school_type  no_of_miniprojects  no_of_projects  \
0        2    3     2            3                   1               1
1        3    1     2            2                   2               1
2        3    4     2            2                   1               1
3        3    4     2            1                   1               1
4        2    3     2            4                   1               1
5        1    1     1            1                   1               1
6        3    3     2            2                   2               1
7        3    3     2            2                   1               1
8        3    2     3            3                   1               1
9        4    4     2            2                   1               1
10       4    4     2            2                   1               1
11       4    4     3            1                   1               1
12       3    3     3            2                   1               1
13       4    4     2            2                   1               1
14       4    3     1            1                   1               1
15       4    3     3            2                   1               1
16       2    3     1            2                   2               1
17       4    4     4            2                   2               1
18       3    3     2            1                   1               1
19       4    4     4            2                   2               1
20       2    2     2            2                   1               1
21       4    4     3            2                   1               1
22       1    1     2            3                   3               3
23       4    4     4            1                   2               2
24       4    4     3            2                   2               1
25       3    3     3            1                   1               1
26       3    3     2            1                   1               1
27       4    4     2            2                   2               1
28       2    4     2            3                   2               2
29       4    4     4            3                   2               1
...    ...  ...   ...          ...                 ...             ...
7495     2    3     2            2                   2               2
7496     4    4     2            2                   1               1
7497     3    3     2            3                   1               1
7498     3    2     3            3                   1               1
7499     3    2     1            2                   1               1
7500     3    3     3            1                   4               2
7501     3    3     2            3                   2               1
7502     2    3     3            2                   2               1
7503     3    4     1            2                   2               1
7504     4    4     3            2                   2               2
7505     4    3     2            2                   1               1
7506     2    1     2            2                   1               1
7507     2    2     2            1                   1               1
7508     3    3     4            2                   1               1
7509     2    2     1            2                   2               1
7510     1    2     1            1                   1               1
7511     4    4     2            2                   1               2
7512     2    4     1            1                   2               1
7513     3    3     1            2                   1               1
7514     2    3     1            2                   2               1
7515     3    3     1            2                   2               2
7516     3    3     3            2                   1               1
7517     3    3     2            2                   3               1
7518     2    3     1            1                   1               1
7519     3    3     2            1                   2               1
7520     3    2     1            2                   1               1
7521     2    3     3            3                   4               3
7522     3    2     1            2                   1               1
7523     2    1     1            1                   2               1
7524     2    2     2            3                   2               1

      coresub_skill  aptitude_skill  problemsolving_skill  programming_skill  \
0                 1               1                     1                  1
1                 1               3                     2                  4
2                 1               2                     3                  3
3                 1               1                     3                  2
4                 1               4                     3                  3
5                 2               2                     3                  2
6                 2               4                     3                  3
7                 2               1                     2                  2
8                 1               2                     3                  5
9                 2               2                     3                  3
10                1               3                     3                  2
11                1               4                     3                  2
12                2               4                     2                  3
13                2               3                     3                  3
14                2               4                     3                  3
15                2               3                     3                  2
16                2               3                     3                  4
17                1               4                     2                  3
18                1               1                     2                  2
19                2               4                     3                  4
20                2               3                     4                  5
21                2               1                     3                  3
22                2               3                     3                  3
23                2               4                     3                  3
24                1               1                     2                  3
25                1               2                     4                  2
26                2               2                     3                  3
27                2               4                     3                  3
28                2               2                     2                  3
29                1               1                     2                  3
...             ...             ...                   ...                ...
7495              1               2                     2                  2
7496              2               1                     2                  3
7497              1               4                     4                  3
7498              1               2                     2                  5
7499              2               3                     4                  2
7500              1               4                     3                  3
7501              2               1                     3                  3
7502              1               1                     2                  3
7503              1               3                     2                  2
7504              1               1                     2                  3
7505              1               2                     2                  3
7506              2               1                     4                  2
7507              2               4                     2                  3
7508              2               2                     3                  3
7509              2               4                     2                  3
7510              2               1                     3                  3
7511              1               1                     3                  3
7512              2               2                     4                  3
7513              1               2                     2                  3
7514              1               1                     2                  2
7515              1               2                     2                  4
7516              2               4                     3                  3
7517              1               4                     4                  3
7518              1               3                     2                  4
7519              2               1                     2                  3
7520              2               2                     3                  3
7521              2               1                     3                  3
7522              1               2                     2                  3
7523              1               2                     2                  2
7524              1               1                     2                  3

      ...   technology_used  sympos_attend  sympos_won  extracurricular  \
0     ...                 1              1           1                1
1     ...                 2              3           2                3
2     ...                 1              4           3                1
3     ...                 1              3           2                1
4     ...                 1              2           1                3
5     ...                 1              3           2                1
6     ...                 1              3           2                1
7     ...                 1              3           3                3
8     ...                 1              3           3                3
9     ...                 1              1           2                2
10    ...                 1              3           3                3
11    ...                 1              2           3                1
12    ...                 1              3           1                2
13    ...                 1              3           1                1
14    ...                 1              3           2                2
15    ...                 1              4           1                2
16    ...                 1              3           3                1
17    ...                 1              4           5                1
18    ...                 1              3           1                4
19    ...                 1              3           2                3
20    ...                 2              3           2                3
21    ...                 1              3           1                3
22    ...                 2              3           3                4
23    ...                 2              4           2                1
24    ...                 1              3           2                2
25    ...                 1              3           2                1
26    ...                 1              4           3                3
27    ...                 1              3           2                3
28    ...                 1              3           3                2
29    ...                 1              3           1                3
...   ...               ...            ...         ...              ...
7495  ...                 1              3           2                2
7496  ...                 1              3           2                1
7497  ...                 1              3           2                1
7498  ...                 1              1           3                4
7499  ...                 1              4           1                4
7500  ...                 2              4           2                3
7501  ...                 1              4           1                1
7502  ...                 1              3           1                1
7503  ...                 1              4           3                1
7504  ...                 1              1           1                4
7505  ...                 1              1           2                1
7506  ...                 1              4           2                2
7507  ...                 1              4           1                2
7508  ...                 1              3           1                4
7509  ...                 1              3           2                4
7510  ...                 1              1           5                1
7511  ...                 1              4           2                3
7512  ...                 1              3           5                2
7513  ...                 1              3           2                3
7514  ...                 1              4           1                3
7515  ...                 3              2           1                1
7516  ...                 1              3           2                3
7517  ...                 2              3           1                4
7518  ...                 1              4           2                1
7519  ...                 2              4           3                4
7520  ...                 1              4           2                2
7521  ...                 4              2           3                2
7522  ...                 1              3           1                1
7523  ...                 1              3           2                1
7524  ...                 1              4           1                1

      learning_style  college_bench  clg_teachers_know  college_performence   \
0                  1              1                  1                     1
1                  2              5                  3                     3
2                  4              3                  3                     3
3                  2              1                  4                     4
4                  1              5                  4                     3
5                  2              5                  3                     3
6                  1              5                  4                     4
7                  4              5                  4                     3
8                  2              5                  4                     3
9                  3              5                  4                     4
10                 2              5                  4                     4
11                 1              3                  4                     4
12                 2              5                  4                     4
13                 2              5                  2                     3
14                 2              5                  4                     4
15                 2              4                  4                     4
16                 1              3                  4                     3
17                 1              5                  4                     4
18                 2              5                  4                     3
19                 2              5                  4                     4
20                 2              4                  3                     4
21                 3              5                  3                     4
22                 2              3                  1                     4
23                 3              3                  4                     4
24                 3              5                  3                     3
25                 2              4                  4                     3
26                 2              4                  3                     3
27                 4              2                  4                     4
28                 4              4                  4                     3
29                 1              4                  4                     3
...              ...            ...                ...                   ...
7495               2              4                  4                     3
7496               2              4                  2                     3
7497               4              4                  4                     4
7498               2              5                  4                     3
7499               1              3                  4                     3
7500               1              4                  3                     3
7501               2              4                  3                     4
7502               3              5                  4                     3
7503               3              3                  4                     3
7504               2              4                  3                     4
7505               2              4                  4                     3
7506               4              3                  4                     3
7507               4              4                  4                     3
7508               1              4                  4                     3
7509               1              2                  4                     3
7510               4              4                  4                     3
7511               1              5                  3                     3
7512               3              4                  4                     3
7513               2              4                  4                     3
7514               3              4                  3                     3
7515               1              3                  4                     3
7516               2              4                  4                     4
7517               1              3                  4                     3
7518               4              4                  4                     4
7519               1              4                  4                     3
7520               1              4                  4                     3
7521               4              1                  3                     3
7522               3              5                  3                     3
7523               2              4                  4                     3
7524               3              5                  3                     3

      college_skills  ROLE
0                  5   100
1                  4   101
2                  4   103
3                  3   100
4                  1   104
5                  5   105
6                  4   106
7                  3   100
8                  3   105
9                  5   107
10                 3   101
11                 4   100
12                 3   106
13                 4   101
14                 3   101
15                 3   106
16                 5   105
17                 4   101
18                 5   100
19                 4   105
20                 4   100
21                 1   108
22                 5   106
23                 4   101
24                 3   105
25                 3   103
26                 4   101
27                 5   106
28                 3   108
29                 1   106
...              ...   ...
7495               1     0
7496               3     0
7497               1     0
7498               1     0
7499               5     0
7500               2     0
7501               2     0
7502               3     0
7503               2     0
7504               4     0
7505               1     0
7506               2     0
7507               3     0
7508               2     0
7509               5     0
7510               2     0
7511               3     0
7512               2     0
7513               5     0
7514               2     0
7515               4     0
7516               1     0
7517               1     0
7518               4     0
7519               5     0
7520               3     0

In [77]:
from sklearn.model_selection import train_test_split
X=df.iloc[0:2100,[0,1,2,5,7,8,9,10,25]]
print(X)
y=df.iloc[0:2100,[0,1,2,5,7,8,9,10]]
print(y)
X=np.array(X)
y=np.array(y)

      sslc  hsc  cgpa  no_of_projects  aptitude_skill  problemsolving_skill  \
0        2    3     2               1               1                     1
1        3    1     2               1               3                     2
2        3    4     2               1               2                     3
3        3    4     2               1               1                     3
4        2    3     2               1               4                     3
5        1    1     1               1               2                     3
6        3    3     2               1               4                     3
7        3    3     2               1               1                     2
8        3    2     3               1               2                     3
9        4    4     2               1               2                     3
10       4    4     2               1               3                     3
11       4    4     3               1               4                     3
12       3    3     3               1               4                     2
13       4    4     2               1               3                     3
14       4    3     1               1               4                     3
15       4    3     3               1               3                     3
16       2    3     1               1               3                     3
17       4    4     4               1               4                     2
18       3    3     2               1               1                     2
19       4    4     4               1               4                     3
20       2    2     2               1               3                     4
21       4    4     3               1               1                     3
22       1    1     2               3               3                     3
23       4    4     4               2               4                     3
24       4    4     3               1               1                     2
25       3    3     3               1               2                     4
26       3    3     2               1               2                     3
27       4    4     2               1               4                     3
28       2    4     2               2               2                     2
29       4    4     4               1               1                     2
...    ...  ...   ...             ...             ...                   ...
2070     2    3     3               1               4                     2
2071     3    4     2               1               1                     3
2072     3    2     2               1               1                     2
2073     3    3     3               1               1                     3
2074     2    2     1               1               2                     1
2075     2    3     3               1               4                     3
2076     3    2     3               1               1                     3
2077     4    4     2               1               2                     3
2078     4    4     2               1               1                     3
2079     3    4     2               2               2                     3
2080     2    2     2               1               3                     3
2081     3    3     1               2               3                     3
2082     3    3     2               1               1                     3
2083     3    3     2               1               1                     4
2084     4    4     3               4               2                     4
2085     3    3     1               1               3                     3
2086     4    4     3               1               2                     2
2087     1    2     1               1               2                     2
2088     1    3     2               1               4                     4
2089     2    1     4               4               4                     4
2090     3    4     2               1               2                     1
2091     4    3     3               1               1                     3
2092     2    2     2               1               1                     3
2093     3    3     2               1               1                     2
2094     4    3     2               1               1                     3
2095     3    3     2               1               2                     2
2096     3    4     2               1               1                     4
2097     4    4     3               1               4                     3
2098     4    4     2               1               4                     4
2099     2    2     2               1               1                     3

      programming_skill  abstractthink_skill  ROLE
0                     1                    1   100
1                     4                    3   101
2                     3                    2   103
3                     2                    2   100
4                     3                    2   104
5                     2                    3   105
6                     3                    3   106
7                     2                    2   100
8                     5                    2   105
9                     3                    3   107
10                    2                    3   101
11                    2                    2   100
12                    3                    3   106
13                    3                    2   101
14                    3                    2   101
15                    2                    3   106
16                    4                    3   105
17                    3                    2   101
18                    2                    2   100
19                    4                    3   105
20                    5                    2   100
21                    3                    1   108
22                    3                    4   106
23                    3                    3   101
24                    3                    2   105
25                    2                    1   103
26                    3                    4   101
27                    3                    2   106
28                    3                    2   108
29                    3                    3   106
...                 ...                  ...   ...
2070                  3                    2     0
2071                  3                    2     0
2072                  3                    2     0
2073                  3                    2     0
2074                  3                    2     0
2075                  4                    4     0
2076                  3                    3     0
2077                  3                    3     0
2078                  2                    2     0
2079                  3                    2     0
2080                  1                    4     0
2081                  3                    2     0
2082                  3                    2     0
2083                  4                    2     0
2084                  2                    3     0
2085                  3                    2     0
2086                  3                    2     0
2087                  2                    2     0
2088                  5                    4     0
2089                  3                    4     0
2090                  3                    1     0
2091                  2                    3     0
2092                  2                    2     0
2093                  3                    1     0
2094                  3                    2     0
2095                  2                    1     0
2096                  3                    3     0
2097                  2                    2     0
2098                  3                    2     0
2099                  3                    1     0

[2100 rows x 9 columns]
      sslc  hsc  cgpa  no_of_projects  aptitude_skill  problemsolving_skill  \
0        2    3     2               1               1                     1
1        3    1     2               1               3                     2
2        3    4     2               1               2                     3
3        3    4     2               1               1                     3
4        2    3     2               1               4                     3
5        1    1     1               1               2                     3
6        3    3     2               1               4                     3
7        3    3     2               1               1                     2
8        3    2     3               1               2                     3
9        4    4     2               1               2                     3
10       4    4     2               1               3                     3
11       4    4     3               1               4                     3
12       3    3     3               1               4                     2
13       4    4     2               1               3                     3
14       4    3     1               1               4                     3
15       4    3     3               1               3                     3
16       2    3     1               1               3                     3
17       4    4     4               1               4                     2
18       3    3     2               1               1                     2
19       4    4     4               1               4                     3
20       2    2     2               1               3                     4
21       4    4     3               1               1                     3
22       1    1     2               3               3                     3
23       4    4     4               2               4                     3
24       4    4     3               1               1                     2
25       3    3     3               1               2                     4
26       3    3     2               1               2                     3
27       4    4     2               1               4                     3
28       2    4     2               2               2                     2
29       4    4     4               1               1                     2
...    ...  ...   ...             ...             ...                   ...
2070     2    3     3               1               4                     2
2071     3    4     2               1               1                     3
2072     3    2     2               1               1                     2
2073     3    3     3               1               1                     3
2074     2    2     1               1               2                     1
2075     2    3     3               1               4                     3
2076     3    2     3               1               1                     3
2077     4    4     2               1               2                     3
2078     4    4     2               1               1                     3
2079     3    4     2               2               2                     3
2080     2    2     2               1               3                     3
2081     3    3     1               2               3                     3
2082     3    3     2               1               1                     3
2083     3    3     2               1               1                     4
2084     4    4     3               4               2                     4
2085     3    3     1               1               3                     3
2086     4    4     3               1               2                     2
2087     1    2     1               1               2                     2
2088     1    3     2               1               4                     4
2089     2    1     4               4               4                     4
2090     3    4     2               1               2                     1
2091     4    3     3               1               1                     3
2092     2    2     2               1               1                     3
2093     3    3     2               1               1                     2
2094     4    3     2               1               1                     3
2095     3    3     2               1               2                     2
2096     3    4     2               1               1                     4
2097     4    4     3               1               4                     3
2098     4    4     2               1               4                     4
2099     2    2     2               1               1                     3

      programming_skill  abstractthink_skill
0                     1                    1
1                     4                    3
2                     3                    2
3                     2                    2
4                     3                    2
5                     2                    3
6                     3                    3
7                     2                    2
8                     5                    2
9                     3                    3
10                    2                    3
11                    2                    2
12                    3                    3
13                    3                    2
14                    3                    2
15                    2                    3
16                    4                    3
17                    3                    2
18                    2                    2
19                    4                    3
20                    5                    2
21                    3                    1
22                    3                    4
23                    3                    3
24                    3                    2
25                    2                    1
26                    3                    4
27                    3                    2
28                    3                    2
29                    3                    3
...                 ...                  ...
2070                  3                    2
2071                  3                    2
2072                  3                    2
2073                  3                    2
2074                  3                    2
2075                  4                    4
2076                  3                    3
2077                  3                    3
2078                  2                    2
2079                  3                    2
2080                  1                    4
2081                  3                    2
2082                  3                    2
2083                  4                    2
2084                  2                    3
2085                  3                    2
2086                  3                    2
2087                  2                    2
2088                  5                    4
2089                  3                    4
2090                  3                    1
2091                  2                    3
2092                  2                    2
2093                  3                    1
2094                  3                    2
2095                  2                    1
2096                  3                    3
2097                  2                    2
2098                  3                    2
2099                  3                    1

[2100 rows x 8 columns]

In [78]:
print(X.shape,"\t",y.shape)

(2100, 9) 	 (2100, 8)

In [79]:
from sklearn import svm
classifier=svm.SVC(kernel='linear',C=1.0)
classifier.fit(X,y)
classifier.predict(X)

ValueError: bad input shape (2100, 8)

In [73]:
x_train, x_test, y_train, y_test = cross_validation.train_test_split(X,y,test_size = 0.2,random_state=5)
y_test_pred = classifier.predict(x_test)

NotFittedError: This SVC instance is not fitted yet. Call 'fit' with appropriate arguments before using this method.

In [47]:
predictions=[round(i) for i in y_test_pred]
accuracy=classifier.score(y_test_pred.reshape(-1,1),predictions)

In [49]:
print("Accuracy: %.2f%%" % ( accuracy * 100.0))

Accuracy: 97.86%